version: '3.8'
services:
  web-server:
    container_name: web-server
    build:
      context: .
      dockerfile: ./build/web-server/Dockerfile
    image: yirmt/advanced-software-group-j-web-server
    volumes:
      - ./src/web-server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:8081
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    tty: true
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: ./build/api-server/prd/Dockerfile
    image: yirmt/advanced-software-group-j-api-server
    volumes:
      - ./src/api-server:/app
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    tty: true
  app-server:
    container_name: app-server
    build: 
      context: .
      dockerfile: ./build/app-server/prd/Dockerfile
    image: yirmt/advanced-software-group-j-app-server
    volumes:
      - ./src/app-server:/app
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    tty: true