version: '3.8'
services:
  web-server:
    container_name: web-server
    image: nginx:latest
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src/web-server/default.conf:/etc/nginx/conf.d/default.conf
  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: ./build/api-server/dev/Dockerfile
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    tty: true
    volumes:
      - ./src/api-server:/app
  app-server:
    container_name: app-server
    build: 
      context: .
      dockerfile: ./build/app-server/dev/Dockerfile
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - ${LOCAL_IP_ADDR}:8081:8081
      - ${LOCAL_IP_ADDR}:8082:8082
      - ${LOCAL_IP_ADDR}:8083:8083
    tty: true
    volumes:
      - ./src/app-server:/app

