version: '3.8'
services:
#  web-server:
#    container_name: web-server
#    image: nginx:latest
#    deploy:
#      resources:
#        reservations:
#          cpus: '0.5'
#          memory: 1G
#        limits:
#          cpus: '1'
#          memory: 2G
#    restart: always
#    ports:
#      - 80:80
#    volumes:
#      - ./build/web-server/default.conf:/etc/nginx/conf.d/default.conf
  api-server:
    container_name: api-server
    build: 
      context: .
      dockerfile: ./build/api-server/dev/Dockerfile
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G
    restart: always
    tty: true
    # テスト用に公開するのは8001
    ports:
      - 8001:8080
    volumes:
      - ./api-server/:/app
#  app-server:
#    container_name: app-server
#    build: 
#      context: .
#      dockerfile: ./build/app-server/dev/Dockerfile
#    deploy:
#      resources:
#        reservations:
#          cpus: '0.5'
#          memory: 1G
#        limits:
#          cpus: '1'
#          memory: 2G
#    restart: always
#    # テスト用に公開するのは8002
#    ports:
#      - 8002:8080
#    volumes:
#      - ./app-server/:/app

